Add gobject introspection run dep
conda-forge/hkl-feedstock pull request #9
Opened 2021-12-06 16:13 UTC by mrakitin

Prompted by https://github.com/bluesky/hklpy/pull/211.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2021-12-06 16:13 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-12-06 16:33 UTC, mrakitin commented
Discussion in https://github.com/bluesky/hklpy/pull/211#discussion_r763168629 is still going on to see if we actually need it. Converted to draft until we come up with the decision.

2023-03-18 22:14 UTC, prjemian requested changes
Suggest closing this PR to move ahead with #13

2023-03-18 22:14 UTC, prjemian commented on recipe/meta.yaml
> +    - gobject-introspection
This change seems redundant.  Let's try building the latest tag (3001) in #13.

2023-09-22 17:01 UTC, prjemian commented
@mrakitin Ok if I close this PR?

2023-09-26 00:55 UTC, mrakitin commented
@prjemian, yes, let's close it and iterate in a newer one.

2023-09-26 00:55 UTC, closed without merging